[package]
name = "ethereum-stories"
version = "0.1.0-0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
anyhow = "1.0.98"
dotenvy = "0.15.7"
tokio = { version = "1.45.1", features = ["full"] }

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
